#pragma once

#include <btl/visibility.h>

#ifdef REACTIVE_EXPORT_SYMBOLS
#define REACTIVE_EXPORT BTL_EXPORT
#define REACTIVE_EXPORT_TEMPLATE BTL_EXPORT_TEMPLATE
#else
#define REACTIVE_EXPORT
#define REACTIVE_EXPORT_TEMPLATE BTL_IMPORT_TEMPLATE
#endif

