# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  submodules: true

- script: |
    sudo apt-get install -y ninja-build
  displayName: 'install dependencies'

- script: |  
    mkdir -p build/clang6-release
    cd build/clang6-release
    CC=clang-6.0 CXX=clang++-6.0 ../meson/meson.py ../.. --buildtype=release
    ninja
    ninja test
  displayName: 'Clang-6 release'
  timeoutInMinutes: 20
