# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

checkout: self
  submodules:true

trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    sudo apt-get -u install-build ninja g++-8
    mkdir -p build/gcc8-release
    cd build/gcc8-release
    CC=gcc-8 CXX=g++-8 ../meson/meson.py ../.. --buildtype=release
    ninja
    ninja test
