# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  submodules: true

- script: |
    sudo apt-get install -y ninja-build clang-7
  displayName: 'install dependencies'

- script: |  
    mkdir -p build/clang7-release
    cd build/clang7-release
    CC=clang-7 CXX=clang++-7 ../meson/meson.py ../.. --buildtype=release
    ninja
    ninja test
  displayName: 'Clang-7 release'
