#include "keycode.h"

#include <string>

namespace ase
{

char const* toString(KeyCode code)
{
    switch (code)
    {
    case KeyCode::space:
        return "space";
    case KeyCode::exclam:
        return "exclam";
    case KeyCode::quotedbl:
        return "quotedbl";
    case KeyCode::numbersign:
        return "numbersign";
    case KeyCode::dollar:
        return "dollar";
    case KeyCode::percent:
        return "percent";
    case KeyCode::ampersand:
        return "ampersand";
    case KeyCode::apostrophe:
        return "apostrophe";
    case KeyCode::parenleft:
        return "parenleft";
    case KeyCode::parenright:
        return "parenright";
    case KeyCode::asterisk:
        return "asterisk";
    case KeyCode::plus:
        return "plus";
    case KeyCode::comma:
        return "comma";
    case KeyCode::minus:
        return "minus";
    case KeyCode::period:
        return "period";
    case KeyCode::slash:
        return "slash";
    case KeyCode::key0:
        return "key0";
    case KeyCode::key1:
        return "key1";
    case KeyCode::key2:
        return "key2";
    case KeyCode::key3:
        return "key3";
    case KeyCode::key4:
        return "key4";
    case KeyCode::key5:
        return "key5";
    case KeyCode::key6:
        return "key6";
    case KeyCode::key7:
        return "key7";
    case KeyCode::key8:
        return "key8";
    case KeyCode::key9:
        return "key9";
    case KeyCode::colon:
        return "colon";
    case KeyCode::semicolon:
        return "semicolon";
    case KeyCode::less:
        return "less";
    case KeyCode::equal:
        return "equal";
    case KeyCode::greater:
        return "greater";
    case KeyCode::question:
        return "question";
    case KeyCode::at:
        return "at";
    case KeyCode::A:
        return "A";
    case KeyCode::B:
        return "B";
    case KeyCode::C:
        return "C";
    case KeyCode::D:
        return "D";
    case KeyCode::E:
        return "E";
    case KeyCode::F:
        return "F";
    case KeyCode::G:
        return "G";
    case KeyCode::H:
        return "H";
    case KeyCode::I:
        return "I";
    case KeyCode::J:
        return "J";
    case KeyCode::K:
        return "K";
    case KeyCode::L:
        return "L";
    case KeyCode::M:
        return "M";
    case KeyCode::N:
        return "N";
    case KeyCode::O:
        return "O";
    case KeyCode::P:
        return "P";
    case KeyCode::Q:
        return "Q";
    case KeyCode::R:
        return "R";
    case KeyCode::S:
        return "S";
    case KeyCode::T:
        return "T";
    case KeyCode::U:
        return "U";
    case KeyCode::V:
        return "V";
    case KeyCode::W:
        return "W";
    case KeyCode::X:
        return "X";
    case KeyCode::Y:
        return "Y";
    case KeyCode::Z:
        return "Z";
    case KeyCode::bracketleft:
        return "bracketleft";
    case KeyCode::backslash:
        return "backslash";
    case KeyCode::bracketright:
        return "bracketright";
    case KeyCode::asciicircum:
        return "asciicircum";
    case KeyCode::underscore:
        return "underscore";
    case KeyCode::grave:
        return "grave";
    case KeyCode::a:
        return "a";
    case KeyCode::b:
        return "b";
    case KeyCode::c:
        return "c";
    case KeyCode::d:
        return "d";
    case KeyCode::e:
        return "e";
    case KeyCode::f:
        return "f";
    case KeyCode::g:
        return "g";
    case KeyCode::h:
        return "h";
    case KeyCode::i:
        return "i";
    case KeyCode::j:
        return "j";
    case KeyCode::k:
        return "k";
    case KeyCode::l:
        return "l";
    case KeyCode::m:
        return "m";
    case KeyCode::n:
        return "n";
    case KeyCode::o:
        return "o";
    case KeyCode::p:
        return "p";
    case KeyCode::q:
        return "q";
    case KeyCode::r:
        return "r";
    case KeyCode::s:
        return "s";
    case KeyCode::t:
        return "t";
    case KeyCode::u:
        return "u";
    case KeyCode::v:
        return "v";
    case KeyCode::w:
        return "w";
    case KeyCode::x:
        return "x";
    case KeyCode::y:
        return "y";
    case KeyCode::z:
        return "z";
    case KeyCode::braceleft:
        return "braceleft";
    case KeyCode::bar:
        return "bar";
    case KeyCode::braceright:
        return "braceright";
    case KeyCode::asciitilde:
        return "asciitilde";
    case KeyCode::nobreakspace:
        return "nobreakspace";
    case KeyCode::exclamdown:
        return "exclamdown";
    case KeyCode::cent:
        return "cent";
    case KeyCode::sterling:
        return "sterling";
    case KeyCode::currency:
        return "currency";
    case KeyCode::yen:
        return "yen";
    case KeyCode::brokenbar:
        return "brokenbar";
    case KeyCode::section:
        return "section";
    case KeyCode::diaeresis:
        return "diaeresis";
    case KeyCode::copyright:
        return "copyright";
    case KeyCode::ordfeminine:
        return "ordfeminine";
    case KeyCode::guillemotleft:
        return "guillemotleft";
    case KeyCode::notsign:
        return "notsign";
    case KeyCode::hyphen:
        return "hyphen";
    case KeyCode::registered:
        return "registered";
    case KeyCode::macron:
        return "macron";
    case KeyCode::degree:
        return "degree";
    case KeyCode::plusminus:
        return "plusminus";
    case KeyCode::twosuperior:
        return "twosuperior";
    case KeyCode::threesuperior:
        return "threesuperior";
    case KeyCode::acute:
        return "acute";
    case KeyCode::mu:
        return "mu";
    case KeyCode::paragraph:
        return "paragraph";
    case KeyCode::periodcentered:
        return "periodcentered";
    case KeyCode::cedilla:
        return "cedilla";
    case KeyCode::onesuperior:
        return "onesuperior";
    case KeyCode::masculine:
        return "masculine";
    case KeyCode::guillemotright:
        return "guillemotright";
    case KeyCode::onequarter:
        return "onequarter";
    case KeyCode::onehalf:
        return "onehalf";
    case KeyCode::threequarters:
        return "threequarters";
    case KeyCode::questiondown:
        return "questiondown";
    case KeyCode::Agrave:
        return "Agrave";
    case KeyCode::Aacute:
        return "Aacute";
    case KeyCode::Acircumflex:
        return "Acircumflex";
    case KeyCode::Atilde:
        return "Atilde";
    case KeyCode::Adiaeresis:
        return "Adiaeresis";
    case KeyCode::Aring:
        return "Aring";
    case KeyCode::AE:
        return "AE";
    case KeyCode::Ccedilla:
        return "Ccedilla";
    case KeyCode::Egrave:
        return "Egrave";
    case KeyCode::Eacute:
        return "Eacute";
    case KeyCode::Ecircumflex:
        return "Ecircumflex";
    case KeyCode::Ediaeresis:
        return "Ediaeresis";
    case KeyCode::Igrave:
        return "Igrave";
    case KeyCode::Iacute:
        return "Iacute";
    case KeyCode::Icircumflex:
        return "Icircumflex";
    case KeyCode::Idiaeresis:
        return "Idiaeresis";
    case KeyCode::ETH:
        return "ETH";
    case KeyCode::Ntilde:
        return "Ntilde";
    case KeyCode::Ograve:
        return "Ograve";
    case KeyCode::Oacute:
        return "Oacute";
    case KeyCode::Ocircumflex:
        return "Ocircumflex";
    case KeyCode::Otilde:
        return "Otilde";
    case KeyCode::Odiaeresis:
        return "Odiaeresis";
    case KeyCode::multiply:
        return "multiply";
    case KeyCode::Oslash:
        return "Oslash";
    case KeyCode::Ugrave:
        return "Ugrave";
    case KeyCode::Uacute:
        return "Uacute";
    case KeyCode::Ucircumflex:
        return "Ucircumflex";
    case KeyCode::Udiaeresis:
        return "Udiaeresis";
    case KeyCode::Yacute:
        return "Yacute";
    case KeyCode::THORN:
        return "THORN";
    case KeyCode::ssharp:
        return "ssharp";
    case KeyCode::agrave:
        return "agrave";
    case KeyCode::aacute:
        return "aacute";
    case KeyCode::acircumflex:
        return "acircumflex";
    case KeyCode::atilde:
        return "atilde";
    case KeyCode::adiaeresis:
        return "adiaeresis";
    case KeyCode::aring:
        return "aring";
    case KeyCode::ae:
        return "ae";
    case KeyCode::ccedilla:
        return "ccedilla";
    case KeyCode::egrave:
        return "egrave";
    case KeyCode::eacute:
        return "eacute";
    case KeyCode::ecircumflex:
        return "ecircumflex";
    case KeyCode::ediaeresis:
        return "ediaeresis";
    case KeyCode::igrave:
        return "igrave";
    case KeyCode::iacute:
        return "iacute";
    case KeyCode::icircumflex:
        return "icircumflex";
    case KeyCode::idiaeresis:
        return "idiaeresis";
    case KeyCode::eth:
        return "eth";
    case KeyCode::ntilde:
        return "ntilde";
    case KeyCode::ograve:
        return "ograve";
    case KeyCode::oacute:
        return "oacute";
    case KeyCode::ocircumflex:
        return "ocircumflex";
    case KeyCode::otilde:
        return "otilde";
    case KeyCode::odiaeresis:
        return "odiaeresis";
    case KeyCode::division:
        return "division";
    case KeyCode::oslash:
        return "oslash";
    case KeyCode::ugrave:
        return "ugrave";
    case KeyCode::uacute:
        return "uacute";
    case KeyCode::ucircumflex:
        return "ucircumflex";
    case KeyCode::udiaeresis:
        return "udiaeresis";
    case KeyCode::yacute:
        return "yacute";
    case KeyCode::thorn:
        return "thorn";
    case KeyCode::ydiaeresis:
        return "ydiaeresis";
    case KeyCode::Aogonek:
        return "Aogonek";
    case KeyCode::breve:
        return "breve";
    case KeyCode::Lstroke:
        return "Lstroke";
    case KeyCode::Lcaron:
        return "Lcaron";
    case KeyCode::Sacute:
        return "Sacute";
    case KeyCode::Scaron:
        return "Scaron";
    case KeyCode::Scedilla:
        return "Scedilla";
    case KeyCode::Tcaron:
        return "Tcaron";
    case KeyCode::Zacute:
        return "Zacute";
    case KeyCode::Zcaron:
        return "Zcaron";
    case KeyCode::Zabovedot:
        return "Zabovedot";
    case KeyCode::aogonek:
        return "aogonek";
    case KeyCode::ogonek:
        return "ogonek";
    case KeyCode::lstroke:
        return "lstroke";
    case KeyCode::lcaron:
        return "lcaron";
    case KeyCode::sacute:
        return "sacute";
    case KeyCode::caron:
        return "caron";
    case KeyCode::scaron:
        return "scaron";
    case KeyCode::scedilla:
        return "scedilla";
    case KeyCode::tcaron:
        return "tcaron";
    case KeyCode::zacute:
        return "zacute";
    case KeyCode::doubleacute:
        return "doubleacute";
    case KeyCode::zcaron:
        return "zcaron";
    case KeyCode::zabovedot:
        return "zabovedot";
    case KeyCode::Racute:
        return "Racute";
    case KeyCode::Abreve:
        return "Abreve";
    case KeyCode::Lacute:
        return "Lacute";
    case KeyCode::Cacute:
        return "Cacute";
    case KeyCode::Ccaron:
        return "Ccaron";
    case KeyCode::Eogonek:
        return "Eogonek";
    case KeyCode::Ecaron:
        return "Ecaron";
    case KeyCode::Dcaron:
        return "Dcaron";
    case KeyCode::Dstroke:
        return "Dstroke";
    case KeyCode::Nacute:
        return "Nacute";
    case KeyCode::Ncaron:
        return "Ncaron";
    case KeyCode::Odoubleacute:
        return "Odoubleacute";
    case KeyCode::Rcaron:
        return "Rcaron";
    case KeyCode::Uring:
        return "Uring";
    case KeyCode::Udoubleacute:
        return "Udoubleacute";
    case KeyCode::Tcedilla:
        return "Tcedilla";
    case KeyCode::racute:
        return "racute";
    case KeyCode::abreve:
        return "abreve";
    case KeyCode::lacute:
        return "lacute";
    case KeyCode::cacute:
        return "cacute";
    case KeyCode::ccaron:
        return "ccaron";
    case KeyCode::eogonek:
        return "eogonek";
    case KeyCode::ecaron:
        return "ecaron";
    case KeyCode::dcaron:
        return "dcaron";
    case KeyCode::dstroke:
        return "dstroke";
    case KeyCode::nacute:
        return "nacute";
    case KeyCode::ncaron:
        return "ncaron";
    case KeyCode::odoubleacute:
        return "odoubleacute";
    case KeyCode::rcaron:
        return "rcaron";
    case KeyCode::uring:
        return "uring";
    case KeyCode::udoubleacute:
        return "udoubleacute";
    case KeyCode::tcedilla:
        return "tcedilla";
    case KeyCode::abovedot:
        return "abovedot";
    case KeyCode::Hstroke:
        return "Hstroke";
    case KeyCode::Hcircumflex:
        return "Hcircumflex";
    case KeyCode::Iabovedot:
        return "Iabovedot";
    case KeyCode::Gbreve:
        return "Gbreve";
    case KeyCode::Jcircumflex:
        return "Jcircumflex";
    case KeyCode::hstroke:
        return "hstroke";
    case KeyCode::hcircumflex:
        return "hcircumflex";
    case KeyCode::idotless:
        return "idotless";
    case KeyCode::gbreve:
        return "gbreve";
    case KeyCode::jcircumflex:
        return "jcircumflex";
    case KeyCode::Cabovedot:
        return "Cabovedot";
    case KeyCode::Ccircumflex:
        return "Ccircumflex";
    case KeyCode::Gabovedot:
        return "Gabovedot";
    case KeyCode::Gcircumflex:
        return "Gcircumflex";
    case KeyCode::Ubreve:
        return "Ubreve";
    case KeyCode::Scircumflex:
        return "Scircumflex";
    case KeyCode::cabovedot:
        return "cabovedot";
    case KeyCode::ccircumflex:
        return "ccircumflex";
    case KeyCode::gabovedot:
        return "gabovedot";
    case KeyCode::gcircumflex:
        return "gcircumflex";
    case KeyCode::ubreve:
        return "ubreve";
    case KeyCode::scircumflex:
        return "scircumflex";
    case KeyCode::kra:
        return "kra";
    case KeyCode::Rcedilla:
        return "Rcedilla";
    case KeyCode::Itilde:
        return "Itilde";
    case KeyCode::Lcedilla:
        return "Lcedilla";
    case KeyCode::Emacron:
        return "Emacron";
    case KeyCode::Gcedilla:
        return "Gcedilla";
    case KeyCode::Tslash:
        return "Tslash";
    case KeyCode::rcedilla:
        return "rcedilla";
    case KeyCode::itilde:
        return "itilde";
    case KeyCode::lcedilla:
        return "lcedilla";
    case KeyCode::emacron:
        return "emacron";
    case KeyCode::gcedilla:
        return "gcedilla";
    case KeyCode::tslash:
        return "tslash";
    case KeyCode::ENG:
        return "ENG";
    case KeyCode::eng:
        return "eng";
    case KeyCode::Amacron:
        return "Amacron";
    case KeyCode::Iogonek:
        return "Iogonek";
    case KeyCode::Eabovedot:
        return "Eabovedot";
    case KeyCode::Imacron:
        return "Imacron";
    case KeyCode::Ncedilla:
        return "Ncedilla";
    case KeyCode::Omacron:
        return "Omacron";
    case KeyCode::Kcedilla:
        return "Kcedilla";
    case KeyCode::Uogonek:
        return "Uogonek";
    case KeyCode::Utilde:
        return "Utilde";
    case KeyCode::Umacron:
        return "Umacron";
    case KeyCode::amacron:
        return "amacron";
    case KeyCode::iogonek:
        return "iogonek";
    case KeyCode::eabovedot:
        return "eabovedot";
    case KeyCode::imacron:
        return "imacron";
    case KeyCode::ncedilla:
        return "ncedilla";
    case KeyCode::omacron:
        return "omacron";
    case KeyCode::kcedilla:
        return "kcedilla";
    case KeyCode::uogonek:
        return "uogonek";
    case KeyCode::utilde:
        return "utilde";
    case KeyCode::umacron:
        return "umacron";
    case KeyCode::overline:
        return "overline";
    case KeyCode::kana_fullstop:
        return "kana_fullstop";
    case KeyCode::kana_openingbracket:
        return "kana_openingbracket";
    case KeyCode::kana_closingbracket:
        return "kana_closingbracket";
    case KeyCode::kana_comma:
        return "kana_comma";
    case KeyCode::kana_conjunctive:
        return "kana_conjunctive";
    case KeyCode::kana_WO:
        return "kana_WO";
    case KeyCode::kana_a:
        return "kana_a";
    case KeyCode::kana_i:
        return "kana_i";
    case KeyCode::kana_u:
        return "kana_u";
    case KeyCode::kana_e:
        return "kana_e";
    case KeyCode::kana_o:
        return "kana_o";
    case KeyCode::kana_ya:
        return "kana_ya";
    case KeyCode::kana_yu:
        return "kana_yu";
    case KeyCode::kana_yo:
        return "kana_yo";
    case KeyCode::kana_tsu:
        return "kana_tsu";
    case KeyCode::prolongedsound:
        return "prolongedsound";
    case KeyCode::kana_A:
        return "kana_A";
    case KeyCode::kana_I:
        return "kana_I";
    case KeyCode::kana_U:
        return "kana_U";
    case KeyCode::kana_E:
        return "kana_E";
    case KeyCode::kana_O:
        return "kana_O";
    case KeyCode::kana_KA:
        return "kana_KA";
    case KeyCode::kana_KI:
        return "kana_KI";
    case KeyCode::kana_KU:
        return "kana_KU";
    case KeyCode::kana_KE:
        return "kana_KE";
    case KeyCode::kana_KO:
        return "kana_KO";
    case KeyCode::kana_SA:
        return "kana_SA";
    case KeyCode::kana_SHI:
        return "kana_SHI";
    case KeyCode::kana_SU:
        return "kana_SU";
    case KeyCode::kana_SE:
        return "kana_SE";
    case KeyCode::kana_SO:
        return "kana_SO";
    case KeyCode::kana_TA:
        return "kana_TA";
    case KeyCode::kana_CHI:
        return "kana_CHI";
    case KeyCode::kana_TSU:
        return "kana_TSU";
    case KeyCode::kana_TE:
        return "kana_TE";
    case KeyCode::kana_TO:
        return "kana_TO";
    case KeyCode::kana_NA:
        return "kana_NA";
    case KeyCode::kana_NI:
        return "kana_NI";
    case KeyCode::kana_NU:
        return "kana_NU";
    case KeyCode::kana_NE:
        return "kana_NE";
    case KeyCode::kana_NO:
        return "kana_NO";
    case KeyCode::kana_HA:
        return "kana_HA";
    case KeyCode::kana_HI:
        return "kana_HI";
    case KeyCode::kana_FU:
        return "kana_FU";
    case KeyCode::kana_HE:
        return "kana_HE";
    case KeyCode::kana_HO:
        return "kana_HO";
    case KeyCode::kana_MA:
        return "kana_MA";
    case KeyCode::kana_MI:
        return "kana_MI";
    case KeyCode::kana_MU:
        return "kana_MU";
    case KeyCode::kana_ME:
        return "kana_ME";
    case KeyCode::kana_MO:
        return "kana_MO";
    case KeyCode::kana_YA:
        return "kana_YA";
    case KeyCode::kana_YU:
        return "kana_YU";
    case KeyCode::kana_YO:
        return "kana_YO";
    case KeyCode::kana_RA:
        return "kana_RA";
    case KeyCode::kana_RI:
        return "kana_RI";
    case KeyCode::kana_RU:
        return "kana_RU";
    case KeyCode::kana_RE:
        return "kana_RE";
    case KeyCode::kana_RO:
        return "kana_RO";
    case KeyCode::kana_WA:
        return "kana_WA";
    case KeyCode::kana_N:
        return "kana_N";
    case KeyCode::voicedsound:
        return "voicedsound";
    case KeyCode::semivoicedsound:
        return "semivoicedsound";
    case KeyCode::Arabic_comma:
        return "Arabic_comma";
    case KeyCode::Arabic_semicolon:
        return "Arabic_semicolon";
    case KeyCode::Arabic_question_mark:
        return "Arabic_question_mark";
    case KeyCode::Arabic_hamza:
        return "Arabic_hamza";
    case KeyCode::Arabic_maddaonalef:
        return "Arabic_maddaonalef";
    case KeyCode::Arabic_hamzaonalef:
        return "Arabic_hamzaonalef";
    case KeyCode::Arabic_hamzaonwaw:
        return "Arabic_hamzaonwaw";
    case KeyCode::Arabic_hamzaunderalef:
        return "Arabic_hamzaunderalef";
    case KeyCode::Arabic_hamzaonyeh:
        return "Arabic_hamzaonyeh";
    case KeyCode::Arabic_alef:
        return "Arabic_alef";
    case KeyCode::Arabic_beh:
        return "Arabic_beh";
    case KeyCode::Arabic_tehmarbuta:
        return "Arabic_tehmarbuta";
    case KeyCode::Arabic_teh:
        return "Arabic_teh";
    case KeyCode::Arabic_theh:
        return "Arabic_theh";
    case KeyCode::Arabic_jeem:
        return "Arabic_jeem";
    case KeyCode::Arabic_hah:
        return "Arabic_hah";
    case KeyCode::Arabic_khah:
        return "Arabic_khah";
    case KeyCode::Arabic_dal:
        return "Arabic_dal";
    case KeyCode::Arabic_thal:
        return "Arabic_thal";
    case KeyCode::Arabic_ra:
        return "Arabic_ra";
    case KeyCode::Arabic_zain:
        return "Arabic_zain";
    case KeyCode::Arabic_seen:
        return "Arabic_seen";
    case KeyCode::Arabic_sheen:
        return "Arabic_sheen";
    case KeyCode::Arabic_sad:
        return "Arabic_sad";
    case KeyCode::Arabic_dad:
        return "Arabic_dad";
    case KeyCode::Arabic_tah:
        return "Arabic_tah";
    case KeyCode::Arabic_zah:
        return "Arabic_zah";
    case KeyCode::Arabic_ain:
        return "Arabic_ain";
    case KeyCode::Arabic_ghain:
        return "Arabic_ghain";
    case KeyCode::Arabic_tatweel:
        return "Arabic_tatweel";
    case KeyCode::Arabic_feh:
        return "Arabic_feh";
    case KeyCode::Arabic_qaf:
        return "Arabic_qaf";
    case KeyCode::Arabic_kaf:
        return "Arabic_kaf";
    case KeyCode::Arabic_lam:
        return "Arabic_lam";
    case KeyCode::Arabic_meem:
        return "Arabic_meem";
    case KeyCode::Arabic_noon:
        return "Arabic_noon";
    case KeyCode::Arabic_ha:
        return "Arabic_ha";
    case KeyCode::Arabic_waw:
        return "Arabic_waw";
    case KeyCode::Arabic_alefmaksura:
        return "Arabic_alefmaksura";
    case KeyCode::Arabic_yeh:
        return "Arabic_yeh";
    case KeyCode::Arabic_fathatan:
        return "Arabic_fathatan";
    case KeyCode::Arabic_dammatan:
        return "Arabic_dammatan";
    case KeyCode::Arabic_kasratan:
        return "Arabic_kasratan";
    case KeyCode::Arabic_fatha:
        return "Arabic_fatha";
    case KeyCode::Arabic_damma:
        return "Arabic_damma";
    case KeyCode::Arabic_kasra:
        return "Arabic_kasra";
    case KeyCode::Arabic_shadda:
        return "Arabic_shadda";
    case KeyCode::Arabic_sukun:
        return "Arabic_sukun";
    case KeyCode::Serbian_dje:
        return "Serbian_dje";
    case KeyCode::Macedonia_gje:
        return "Macedonia_gje";
    case KeyCode::Cyrillic_io:
        return "Cyrillic_io";
    case KeyCode::Ukrainian_ie:
        return "Ukrainian_ie";
    case KeyCode::Macedonia_dse:
        return "Macedonia_dse";
    case KeyCode::Ukrainian_i:
        return "Ukrainian_i";
    case KeyCode::Ukrainian_yi:
        return "Ukrainian_yi";
    case KeyCode::Cyrillic_je:
        return "Cyrillic_je";
    case KeyCode::Cyrillic_lje:
        return "Cyrillic_lje";
    case KeyCode::Cyrillic_nje:
        return "Cyrillic_nje";
    case KeyCode::Serbian_tshe:
        return "Serbian_tshe";
    case KeyCode::Macedonia_kje:
        return "Macedonia_kje";
    case KeyCode::Ukrainian_ghe_with_upturn:
        return "Ukrainian_ghe_with_upturn";
    case KeyCode::Byelorussian_shortu:
        return "Byelorussian_shortu";
    case KeyCode::Cyrillic_dzhe:
        return "Cyrillic_dzhe";
    case KeyCode::numerosign:
        return "numerosign";
    case KeyCode::Serbian_DJE:
        return "Serbian_DJE";
    case KeyCode::Macedonia_GJE:
        return "Macedonia_GJE";
    case KeyCode::Cyrillic_IO:
        return "Cyrillic_IO";
    case KeyCode::Ukrainian_IE:
        return "Ukrainian_IE";
    case KeyCode::Macedonia_DSE:
        return "Macedonia_DSE";
    case KeyCode::Ukrainian_I:
        return "Ukrainian_I";
    case KeyCode::Ukrainian_YI:
        return "Ukrainian_YI";
    case KeyCode::Cyrillic_JE:
        return "Cyrillic_JE";
    case KeyCode::Cyrillic_LJE:
        return "Cyrillic_LJE";
    case KeyCode::Cyrillic_NJE:
        return "Cyrillic_NJE";
    case KeyCode::Serbian_TSHE:
        return "Serbian_TSHE";
    case KeyCode::Macedonia_KJE:
        return "Macedonia_KJE";
    case KeyCode::Ukrainian_GHE_WITH_UPTURN:
        return "Ukrainian_GHE_WITH_UPTURN";
    case KeyCode::Byelorussian_SHORTU:
        return "Byelorussian_SHORTU";
    case KeyCode::Cyrillic_DZHE:
        return "Cyrillic_DZHE";
    case KeyCode::Cyrillic_yu:
        return "Cyrillic_yu";
    case KeyCode::Cyrillic_a:
        return "Cyrillic_a";
    case KeyCode::Cyrillic_be:
        return "Cyrillic_be";
    case KeyCode::Cyrillic_tse:
        return "Cyrillic_tse";
    case KeyCode::Cyrillic_de:
        return "Cyrillic_de";
    case KeyCode::Cyrillic_ie:
        return "Cyrillic_ie";
    case KeyCode::Cyrillic_ef:
        return "Cyrillic_ef";
    case KeyCode::Cyrillic_ghe:
        return "Cyrillic_ghe";
    case KeyCode::Cyrillic_ha:
        return "Cyrillic_ha";
    case KeyCode::Cyrillic_i:
        return "Cyrillic_i";
    case KeyCode::Cyrillic_shorti:
        return "Cyrillic_shorti";
    case KeyCode::Cyrillic_ka:
        return "Cyrillic_ka";
    case KeyCode::Cyrillic_el:
        return "Cyrillic_el";
    case KeyCode::Cyrillic_em:
        return "Cyrillic_em";
    case KeyCode::Cyrillic_en:
        return "Cyrillic_en";
    case KeyCode::Cyrillic_o:
        return "Cyrillic_o";
    case KeyCode::Cyrillic_pe:
        return "Cyrillic_pe";
    case KeyCode::Cyrillic_ya:
        return "Cyrillic_ya";
    case KeyCode::Cyrillic_er:
        return "Cyrillic_er";
    case KeyCode::Cyrillic_es:
        return "Cyrillic_es";
    case KeyCode::Cyrillic_te:
        return "Cyrillic_te";
    case KeyCode::Cyrillic_u:
        return "Cyrillic_u";
    case KeyCode::Cyrillic_zhe:
        return "Cyrillic_zhe";
    case KeyCode::Cyrillic_ve:
        return "Cyrillic_ve";
    case KeyCode::Cyrillic_softsign:
        return "Cyrillic_softsign";
    case KeyCode::Cyrillic_yeru:
        return "Cyrillic_yeru";
    case KeyCode::Cyrillic_ze:
        return "Cyrillic_ze";
    case KeyCode::Cyrillic_sha:
        return "Cyrillic_sha";
    case KeyCode::Cyrillic_e:
        return "Cyrillic_e";
    case KeyCode::Cyrillic_shcha:
        return "Cyrillic_shcha";
    case KeyCode::Cyrillic_che:
        return "Cyrillic_che";
    case KeyCode::Cyrillic_hardsign:
        return "Cyrillic_hardsign";
    case KeyCode::Cyrillic_YU:
        return "Cyrillic_YU";
    case KeyCode::Cyrillic_A:
        return "Cyrillic_A";
    case KeyCode::Cyrillic_BE:
        return "Cyrillic_BE";
    case KeyCode::Cyrillic_TSE:
        return "Cyrillic_TSE";
    case KeyCode::Cyrillic_DE:
        return "Cyrillic_DE";
    case KeyCode::Cyrillic_IE:
        return "Cyrillic_IE";
    case KeyCode::Cyrillic_EF:
        return "Cyrillic_EF";
    case KeyCode::Cyrillic_GHE:
        return "Cyrillic_GHE";
    case KeyCode::Cyrillic_HA:
        return "Cyrillic_HA";
    case KeyCode::Cyrillic_I:
        return "Cyrillic_I";
    case KeyCode::Cyrillic_SHORTI:
        return "Cyrillic_SHORTI";
    case KeyCode::Cyrillic_KA:
        return "Cyrillic_KA";
    case KeyCode::Cyrillic_EL:
        return "Cyrillic_EL";
    case KeyCode::Cyrillic_EM:
        return "Cyrillic_EM";
    case KeyCode::Cyrillic_EN:
        return "Cyrillic_EN";
    case KeyCode::Cyrillic_O:
        return "Cyrillic_O";
    case KeyCode::Cyrillic_PE:
        return "Cyrillic_PE";
    case KeyCode::Cyrillic_YA:
        return "Cyrillic_YA";
    case KeyCode::Cyrillic_ER:
        return "Cyrillic_ER";
    case KeyCode::Cyrillic_ES:
        return "Cyrillic_ES";
    case KeyCode::Cyrillic_TE:
        return "Cyrillic_TE";
    case KeyCode::Cyrillic_U:
        return "Cyrillic_U";
    case KeyCode::Cyrillic_ZHE:
        return "Cyrillic_ZHE";
    case KeyCode::Cyrillic_VE:
        return "Cyrillic_VE";
    case KeyCode::Cyrillic_SOFTSIGN:
        return "Cyrillic_SOFTSIGN";
    case KeyCode::Cyrillic_YERU:
        return "Cyrillic_YERU";
    case KeyCode::Cyrillic_ZE:
        return "Cyrillic_ZE";
    case KeyCode::Cyrillic_SHA:
        return "Cyrillic_SHA";
    case KeyCode::Cyrillic_E:
        return "Cyrillic_E";
    case KeyCode::Cyrillic_SHCHA:
        return "Cyrillic_SHCHA";
    case KeyCode::Cyrillic_CHE:
        return "Cyrillic_CHE";
    case KeyCode::Cyrillic_HARDSIGN:
        return "Cyrillic_HARDSIGN";
    case KeyCode::Greek_ALPHAaccent:
        return "Greek_ALPHAaccent";
    case KeyCode::Greek_EPSILONaccent:
        return "Greek_EPSILONaccent";
    case KeyCode::Greek_ETAaccent:
        return "Greek_ETAaccent";
    case KeyCode::Greek_IOTAaccent:
        return "Greek_IOTAaccent";
    case KeyCode::Greek_IOTAdieresis:
        return "Greek_IOTAdieresis";
    case KeyCode::Greek_OMICRONaccent:
        return "Greek_OMICRONaccent";
    case KeyCode::Greek_UPSILONaccent:
        return "Greek_UPSILONaccent";
    case KeyCode::Greek_UPSILONdieresis:
        return "Greek_UPSILONdieresis";
    case KeyCode::Greek_OMEGAaccent:
        return "Greek_OMEGAaccent";
    case KeyCode::Greek_accentdieresis:
        return "Greek_accentdieresis";
    case KeyCode::Greek_horizbar:
        return "Greek_horizbar";
    case KeyCode::Greek_alphaaccent:
        return "Greek_alphaaccent";
    case KeyCode::Greek_epsilonaccent:
        return "Greek_epsilonaccent";
    case KeyCode::Greek_etaaccent:
        return "Greek_etaaccent";
    case KeyCode::Greek_iotaaccent:
        return "Greek_iotaaccent";
    case KeyCode::Greek_iotadieresis:
        return "Greek_iotadieresis";
    case KeyCode::Greek_iotaaccentdieresis:
        return "Greek_iotaaccentdieresis";
    case KeyCode::Greek_omicronaccent:
        return "Greek_omicronaccent";
    case KeyCode::Greek_upsilonaccent:
        return "Greek_upsilonaccent";
    case KeyCode::Greek_upsilondieresis:
        return "Greek_upsilondieresis";
    case KeyCode::Greek_upsilonaccentdieresis:
        return "Greek_upsilonaccentdieresis";
    case KeyCode::Greek_omegaaccent:
        return "Greek_omegaaccent";
    case KeyCode::Greek_ALPHA:
        return "Greek_ALPHA";
    case KeyCode::Greek_BETA:
        return "Greek_BETA";
    case KeyCode::Greek_GAMMA:
        return "Greek_GAMMA";
    case KeyCode::Greek_DELTA:
        return "Greek_DELTA";
    case KeyCode::Greek_EPSILON:
        return "Greek_EPSILON";
    case KeyCode::Greek_ZETA:
        return "Greek_ZETA";
    case KeyCode::Greek_ETA:
        return "Greek_ETA";
    case KeyCode::Greek_THETA:
        return "Greek_THETA";
    case KeyCode::Greek_IOTA:
        return "Greek_IOTA";
    case KeyCode::Greek_KAPPA:
        return "Greek_KAPPA";
    case KeyCode::Greek_LAMDA:
        return "Greek_LAMDA";
    case KeyCode::Greek_MU:
        return "Greek_MU";
    case KeyCode::Greek_NU:
        return "Greek_NU";
    case KeyCode::Greek_XI:
        return "Greek_XI";
    case KeyCode::Greek_OMICRON:
        return "Greek_OMICRON";
    case KeyCode::Greek_PI:
        return "Greek_PI";
    case KeyCode::Greek_RHO:
        return "Greek_RHO";
    case KeyCode::Greek_SIGMA:
        return "Greek_SIGMA";
    case KeyCode::Greek_TAU:
        return "Greek_TAU";
    case KeyCode::Greek_UPSILON:
        return "Greek_UPSILON";
    case KeyCode::Greek_PHI:
        return "Greek_PHI";
    case KeyCode::Greek_CHI:
        return "Greek_CHI";
    case KeyCode::Greek_PSI:
        return "Greek_PSI";
    case KeyCode::Greek_OMEGA:
        return "Greek_OMEGA";
    case KeyCode::Greek_alpha:
        return "Greek_alpha";
    case KeyCode::Greek_beta:
        return "Greek_beta";
    case KeyCode::Greek_gamma:
        return "Greek_gamma";
    case KeyCode::Greek_delta:
        return "Greek_delta";
    case KeyCode::Greek_epsilon:
        return "Greek_epsilon";
    case KeyCode::Greek_zeta:
        return "Greek_zeta";
    case KeyCode::Greek_eta:
        return "Greek_eta";
    case KeyCode::Greek_theta:
        return "Greek_theta";
    case KeyCode::Greek_iota:
        return "Greek_iota";
    case KeyCode::Greek_kappa:
        return "Greek_kappa";
    case KeyCode::Greek_lamda:
        return "Greek_lamda";
    case KeyCode::Greek_mu:
        return "Greek_mu";
    case KeyCode::Greek_nu:
        return "Greek_nu";
    case KeyCode::Greek_xi:
        return "Greek_xi";
    case KeyCode::Greek_omicron:
        return "Greek_omicron";
    case KeyCode::Greek_pi:
        return "Greek_pi";
    case KeyCode::Greek_rho:
        return "Greek_rho";
    case KeyCode::Greek_sigma:
        return "Greek_sigma";
    case KeyCode::Greek_finalsmallsigma:
        return "Greek_finalsmallsigma";
    case KeyCode::Greek_tau:
        return "Greek_tau";
    case KeyCode::Greek_upsilon:
        return "Greek_upsilon";
    case KeyCode::Greek_phi:
        return "Greek_phi";
    case KeyCode::Greek_chi:
        return "Greek_chi";
    case KeyCode::Greek_psi:
        return "Greek_psi";
    case KeyCode::Greek_omega:
        return "Greek_omega";
    case KeyCode::leftradical:
        return "leftradical";
    case KeyCode::topleftradical:
        return "topleftradical";
    case KeyCode::horizconnector:
        return "horizconnector";
    case KeyCode::topintegral:
        return "topintegral";
    case KeyCode::botintegral:
        return "botintegral";
    case KeyCode::vertconnector:
        return "vertconnector";
    case KeyCode::topleftsqbracket:
        return "topleftsqbracket";
    case KeyCode::botleftsqbracket:
        return "botleftsqbracket";
    case KeyCode::toprightsqbracket:
        return "toprightsqbracket";
    case KeyCode::botrightsqbracket:
        return "botrightsqbracket";
    case KeyCode::topleftparens:
        return "topleftparens";
    case KeyCode::botleftparens:
        return "botleftparens";
    case KeyCode::toprightparens:
        return "toprightparens";
    case KeyCode::botrightparens:
        return "botrightparens";
    case KeyCode::leftmiddlecurlybrace:
        return "leftmiddlecurlybrace";
    case KeyCode::rightmiddlecurlybrace:
        return "rightmiddlecurlybrace";
    case KeyCode::topleftsummation:
        return "topleftsummation";
    case KeyCode::botleftsummation:
        return "botleftsummation";
    case KeyCode::topvertsummationconnector:
        return "topvertsummationconnector";
    case KeyCode::botvertsummationconnector:
        return "botvertsummationconnector";
    case KeyCode::toprightsummation:
        return "toprightsummation";
    case KeyCode::botrightsummation:
        return "botrightsummation";
    case KeyCode::rightmiddlesummation:
        return "rightmiddlesummation";
    case KeyCode::lessthanequal:
        return "lessthanequal";
    case KeyCode::notequal:
        return "notequal";
    case KeyCode::greaterthanequal:
        return "greaterthanequal";
    case KeyCode::integral:
        return "integral";
    case KeyCode::therefore:
        return "therefore";
    case KeyCode::variation:
        return "variation";
    case KeyCode::infinity:
        return "infinity";
    case KeyCode::nabla:
        return "nabla";
    case KeyCode::approximate:
        return "approximate";
    case KeyCode::similarequal:
        return "similarequal";
    case KeyCode::ifonlyif:
        return "ifonlyif";
    case KeyCode::implies:
        return "implies";
    case KeyCode::identical:
        return "identical";
    case KeyCode::radical:
        return "radical";
    case KeyCode::includedin:
        return "includedin";
    case KeyCode::includes:
        return "includes";
    case KeyCode::intersection:
        return "intersection";
    case KeyCode::keyunion:
        return "keyunion";
    case KeyCode::logicaland:
        return "logicaland";
    case KeyCode::logicalor:
        return "logicalor";
    case KeyCode::partialderivative:
        return "partialderivative";
    case KeyCode::function:
        return "function";
    case KeyCode::leftarrow:
        return "leftarrow";
    case KeyCode::uparrow:
        return "uparrow";
    case KeyCode::rightarrow:
        return "rightarrow";
    case KeyCode::downarrow:
        return "downarrow";
    case KeyCode::blank:
        return "blank";
    case KeyCode::soliddiamond:
        return "soliddiamond";
    case KeyCode::checkerboard:
        return "checkerboard";
    case KeyCode::ht:
        return "ht";
    case KeyCode::ff:
        return "ff";
    case KeyCode::cr:
        return "cr";
    case KeyCode::lf:
        return "lf";
    case KeyCode::nl:
        return "nl";
    case KeyCode::vt:
        return "vt";
    case KeyCode::lowrightcorner:
        return "lowrightcorner";
    case KeyCode::uprightcorner:
        return "uprightcorner";
    case KeyCode::upleftcorner:
        return "upleftcorner";
    case KeyCode::lowleftcorner:
        return "lowleftcorner";
    case KeyCode::crossinglines:
        return "crossinglines";
    case KeyCode::horizlinescan1:
        return "horizlinescan1";
    case KeyCode::horizlinescan3:
        return "horizlinescan3";
    case KeyCode::horizlinescan5:
        return "horizlinescan5";
    case KeyCode::horizlinescan7:
        return "horizlinescan7";
    case KeyCode::horizlinescan9:
        return "horizlinescan9";
    case KeyCode::leftt:
        return "leftt";
    case KeyCode::rightt:
        return "rightt";
    case KeyCode::bott:
        return "bott";
    case KeyCode::topt:
        return "topt";
    case KeyCode::vertbar:
        return "vertbar";
    case KeyCode::emspace:
        return "emspace";
    case KeyCode::enspace:
        return "enspace";
    case KeyCode::em3space:
        return "em3space";
    case KeyCode::em4space:
        return "em4space";
    case KeyCode::digitspace:
        return "digitspace";
    case KeyCode::punctspace:
        return "punctspace";
    case KeyCode::thinspace:
        return "thinspace";
    case KeyCode::hairspace:
        return "hairspace";
    case KeyCode::emdash:
        return "emdash";
    case KeyCode::endash:
        return "endash";
    case KeyCode::signifblank:
        return "signifblank";
    case KeyCode::ellipsis:
        return "ellipsis";
    case KeyCode::doubbaselinedot:
        return "doubbaselinedot";
    case KeyCode::onethird:
        return "onethird";
    case KeyCode::twothirds:
        return "twothirds";
    case KeyCode::onefifth:
        return "onefifth";
    case KeyCode::twofifths:
        return "twofifths";
    case KeyCode::threefifths:
        return "threefifths";
    case KeyCode::fourfifths:
        return "fourfifths";
    case KeyCode::onesixth:
        return "onesixth";
    case KeyCode::fivesixths:
        return "fivesixths";
    case KeyCode::careof:
        return "careof";
    case KeyCode::figdash:
        return "figdash";
    case KeyCode::leftanglebracket:
        return "leftanglebracket";
    case KeyCode::decimalpoint:
        return "decimalpoint";
    case KeyCode::rightanglebracket:
        return "rightanglebracket";
    case KeyCode::marker:
        return "marker";
    case KeyCode::oneeighth:
        return "oneeighth";
    case KeyCode::threeeighths:
        return "threeeighths";
    case KeyCode::fiveeighths:
        return "fiveeighths";
    case KeyCode::seveneighths:
        return "seveneighths";
    case KeyCode::trademark:
        return "trademark";
    case KeyCode::signaturemark:
        return "signaturemark";
    case KeyCode::trademarkincircle:
        return "trademarkincircle";
    case KeyCode::leftopentriangle:
        return "leftopentriangle";
    case KeyCode::rightopentriangle:
        return "rightopentriangle";
    case KeyCode::emopencircle:
        return "emopencircle";
    case KeyCode::emopenrectangle:
        return "emopenrectangle";
    case KeyCode::leftsinglequotemark:
        return "leftsinglequotemark";
    case KeyCode::rightsinglequotemark:
        return "rightsinglequotemark";
    case KeyCode::leftdoublequotemark:
        return "leftdoublequotemark";
    case KeyCode::rightdoublequotemark:
        return "rightdoublequotemark";
    case KeyCode::prescription:
        return "prescription";
    case KeyCode::permille:
        return "permille";
    case KeyCode::minutes:
        return "minutes";
    case KeyCode::seconds:
        return "seconds";
    case KeyCode::latincross:
        return "latincross";
    case KeyCode::hexagram:
        return "hexagram";
    case KeyCode::filledrectbullet:
        return "filledrectbullet";
    case KeyCode::filledlefttribullet:
        return "filledlefttribullet";
    case KeyCode::filledrighttribullet:
        return "filledrighttribullet";
    case KeyCode::emfilledcircle:
        return "emfilledcircle";
    case KeyCode::emfilledrect:
        return "emfilledrect";
    case KeyCode::enopencircbullet:
        return "enopencircbullet";
    case KeyCode::enopensquarebullet:
        return "enopensquarebullet";
    case KeyCode::openrectbullet:
        return "openrectbullet";
    case KeyCode::opentribulletup:
        return "opentribulletup";
    case KeyCode::opentribulletdown:
        return "opentribulletdown";
    case KeyCode::openstar:
        return "openstar";
    case KeyCode::enfilledcircbullet:
        return "enfilledcircbullet";
    case KeyCode::enfilledsqbullet:
        return "enfilledsqbullet";
    case KeyCode::filledtribulletup:
        return "filledtribulletup";
    case KeyCode::filledtribulletdown:
        return "filledtribulletdown";
    case KeyCode::leftpointer:
        return "leftpointer";
    case KeyCode::rightpointer:
        return "rightpointer";
    case KeyCode::club:
        return "club";
    case KeyCode::diamond:
        return "diamond";
    case KeyCode::heart:
        return "heart";
    case KeyCode::maltesecross:
        return "maltesecross";
    case KeyCode::dagger:
        return "dagger";
    case KeyCode::doubledagger:
        return "doubledagger";
    case KeyCode::checkmark:
        return "checkmark";
    case KeyCode::ballotcross:
        return "ballotcross";
    case KeyCode::musicalsharp:
        return "musicalsharp";
    case KeyCode::musicalflat:
        return "musicalflat";
    case KeyCode::malesymbol:
        return "malesymbol";
    case KeyCode::femalesymbol:
        return "femalesymbol";
    case KeyCode::telephone:
        return "telephone";
    case KeyCode::telephonerecorder:
        return "telephonerecorder";
    case KeyCode::phonographcopyright:
        return "phonographcopyright";
    case KeyCode::caret:
        return "caret";
    case KeyCode::singlelowquotemark:
        return "singlelowquotemark";
    case KeyCode::doublelowquotemark:
        return "doublelowquotemark";
    case KeyCode::cursor:
        return "cursor";
    case KeyCode::leftcaret:
        return "leftcaret";
    case KeyCode::rightcaret:
        return "rightcaret";
    case KeyCode::downcaret:
        return "downcaret";
    case KeyCode::upcaret:
        return "upcaret";
    case KeyCode::overbar:
        return "overbar";
    case KeyCode::downtack:
        return "downtack";
    case KeyCode::upshoe:
        return "upshoe";
    case KeyCode::downstile:
        return "downstile";
    case KeyCode::underbar:
        return "underbar";
    case KeyCode::jot:
        return "jot";
    case KeyCode::quad:
        return "quad";
    case KeyCode::uptack:
        return "uptack";
    case KeyCode::circle:
        return "circle";
    case KeyCode::upstile:
        return "upstile";
    case KeyCode::downshoe:
        return "downshoe";
    case KeyCode::rightshoe:
        return "rightshoe";
    case KeyCode::leftshoe:
        return "leftshoe";
    case KeyCode::lefttack:
        return "lefttack";
    case KeyCode::righttack:
        return "righttack";
    case KeyCode::hebrew_doublelowline:
        return "hebrew_doublelowline";
    case KeyCode::hebrew_aleph:
        return "hebrew_aleph";
    case KeyCode::hebrew_bet:
        return "hebrew_bet";
    case KeyCode::hebrew_gimel:
        return "hebrew_gimel";
    case KeyCode::hebrew_dalet:
        return "hebrew_dalet";
    case KeyCode::hebrew_he:
        return "hebrew_he";
    case KeyCode::hebrew_waw:
        return "hebrew_waw";
    case KeyCode::hebrew_zain:
        return "hebrew_zain";
    case KeyCode::hebrew_chet:
        return "hebrew_chet";
    case KeyCode::hebrew_tet:
        return "hebrew_tet";
    case KeyCode::hebrew_yod:
        return "hebrew_yod";
    case KeyCode::hebrew_finalkaph:
        return "hebrew_finalkaph";
    case KeyCode::hebrew_kaph:
        return "hebrew_kaph";
    case KeyCode::hebrew_lamed:
        return "hebrew_lamed";
    case KeyCode::hebrew_finalmem:
        return "hebrew_finalmem";
    case KeyCode::hebrew_mem:
        return "hebrew_mem";
    case KeyCode::hebrew_finalnun:
        return "hebrew_finalnun";
    case KeyCode::hebrew_nun:
        return "hebrew_nun";
    case KeyCode::hebrew_samech:
        return "hebrew_samech";
    case KeyCode::hebrew_ayin:
        return "hebrew_ayin";
    case KeyCode::hebrew_finalpe:
        return "hebrew_finalpe";
    case KeyCode::hebrew_pe:
        return "hebrew_pe";
    case KeyCode::hebrew_finalzade:
        return "hebrew_finalzade";
    case KeyCode::hebrew_zade:
        return "hebrew_zade";
    case KeyCode::hebrew_qoph:
        return "hebrew_qoph";
    case KeyCode::hebrew_resh:
        return "hebrew_resh";
    case KeyCode::hebrew_shin:
        return "hebrew_shin";
    case KeyCode::hebrew_taw:
        return "hebrew_taw";
    case KeyCode::Thai_kokai:
        return "Thai_kokai";
    case KeyCode::Thai_khokhai:
        return "Thai_khokhai";
    case KeyCode::Thai_khokhuat:
        return "Thai_khokhuat";
    case KeyCode::Thai_khokhwai:
        return "Thai_khokhwai";
    case KeyCode::Thai_khokhon:
        return "Thai_khokhon";
    case KeyCode::Thai_khorakhang:
        return "Thai_khorakhang";
    case KeyCode::Thai_ngongu:
        return "Thai_ngongu";
    case KeyCode::Thai_chochan:
        return "Thai_chochan";
    case KeyCode::Thai_choching:
        return "Thai_choching";
    case KeyCode::Thai_chochang:
        return "Thai_chochang";
    case KeyCode::Thai_soso:
        return "Thai_soso";
    case KeyCode::Thai_chochoe:
        return "Thai_chochoe";
    case KeyCode::Thai_yoying:
        return "Thai_yoying";
    case KeyCode::Thai_dochada:
        return "Thai_dochada";
    case KeyCode::Thai_topatak:
        return "Thai_topatak";
    case KeyCode::Thai_thothan:
        return "Thai_thothan";
    case KeyCode::Thai_thonangmontho:
        return "Thai_thonangmontho";
    case KeyCode::Thai_thophuthao:
        return "Thai_thophuthao";
    case KeyCode::Thai_nonen:
        return "Thai_nonen";
    case KeyCode::Thai_dodek:
        return "Thai_dodek";
    case KeyCode::Thai_totao:
        return "Thai_totao";
    case KeyCode::Thai_thothung:
        return "Thai_thothung";
    case KeyCode::Thai_thothahan:
        return "Thai_thothahan";
    case KeyCode::Thai_thothong:
        return "Thai_thothong";
    case KeyCode::Thai_nonu:
        return "Thai_nonu";
    case KeyCode::Thai_bobaimai:
        return "Thai_bobaimai";
    case KeyCode::Thai_popla:
        return "Thai_popla";
    case KeyCode::Thai_phophung:
        return "Thai_phophung";
    case KeyCode::Thai_fofa:
        return "Thai_fofa";
    case KeyCode::Thai_phophan:
        return "Thai_phophan";
    case KeyCode::Thai_fofan:
        return "Thai_fofan";
    case KeyCode::Thai_phosamphao:
        return "Thai_phosamphao";
    case KeyCode::Thai_moma:
        return "Thai_moma";
    case KeyCode::Thai_yoyak:
        return "Thai_yoyak";
    case KeyCode::Thai_rorua:
        return "Thai_rorua";
    case KeyCode::Thai_ru:
        return "Thai_ru";
    case KeyCode::Thai_loling:
        return "Thai_loling";
    case KeyCode::Thai_lu:
        return "Thai_lu";
    case KeyCode::Thai_wowaen:
        return "Thai_wowaen";
    case KeyCode::Thai_sosala:
        return "Thai_sosala";
    case KeyCode::Thai_sorusi:
        return "Thai_sorusi";
    case KeyCode::Thai_sosua:
        return "Thai_sosua";
    case KeyCode::Thai_hohip:
        return "Thai_hohip";
    case KeyCode::Thai_lochula:
        return "Thai_lochula";
    case KeyCode::Thai_oang:
        return "Thai_oang";
    case KeyCode::Thai_honokhuk:
        return "Thai_honokhuk";
    case KeyCode::Thai_paiyannoi:
        return "Thai_paiyannoi";
    case KeyCode::Thai_saraa:
        return "Thai_saraa";
    case KeyCode::Thai_maihanakat:
        return "Thai_maihanakat";
    case KeyCode::Thai_saraaa:
        return "Thai_saraaa";
    case KeyCode::Thai_saraam:
        return "Thai_saraam";
    case KeyCode::Thai_sarai:
        return "Thai_sarai";
    case KeyCode::Thai_saraii:
        return "Thai_saraii";
    case KeyCode::Thai_saraue:
        return "Thai_saraue";
    case KeyCode::Thai_sarauee:
        return "Thai_sarauee";
    case KeyCode::Thai_sarau:
        return "Thai_sarau";
    case KeyCode::Thai_sarauu:
        return "Thai_sarauu";
    case KeyCode::Thai_phinthu:
        return "Thai_phinthu";
    case KeyCode::Thai_maihanakat_maitho:
        return "Thai_maihanakat_maitho";
    case KeyCode::Thai_baht:
        return "Thai_baht";
    case KeyCode::Thai_sarae:
        return "Thai_sarae";
    case KeyCode::Thai_saraae:
        return "Thai_saraae";
    case KeyCode::Thai_sarao:
        return "Thai_sarao";
    case KeyCode::Thai_saraaimaimuan:
        return "Thai_saraaimaimuan";
    case KeyCode::Thai_saraaimaimalai:
        return "Thai_saraaimaimalai";
    case KeyCode::Thai_lakkhangyao:
        return "Thai_lakkhangyao";
    case KeyCode::Thai_maiyamok:
        return "Thai_maiyamok";
    case KeyCode::Thai_maitaikhu:
        return "Thai_maitaikhu";
    case KeyCode::Thai_maiek:
        return "Thai_maiek";
    case KeyCode::Thai_maitho:
        return "Thai_maitho";
    case KeyCode::Thai_maitri:
        return "Thai_maitri";
    case KeyCode::Thai_maichattawa:
        return "Thai_maichattawa";
    case KeyCode::Thai_thanthakhat:
        return "Thai_thanthakhat";
    case KeyCode::Thai_nikhahit:
        return "Thai_nikhahit";
    case KeyCode::Thai_leksun:
        return "Thai_leksun";
    case KeyCode::Thai_leknung:
        return "Thai_leknung";
    case KeyCode::Thai_leksong:
        return "Thai_leksong";
    case KeyCode::Thai_leksam:
        return "Thai_leksam";
    case KeyCode::Thai_leksi:
        return "Thai_leksi";
    case KeyCode::Thai_lekha:
        return "Thai_lekha";
    case KeyCode::Thai_lekhok:
        return "Thai_lekhok";
    case KeyCode::Thai_lekchet:
        return "Thai_lekchet";
    case KeyCode::Thai_lekpaet:
        return "Thai_lekpaet";
    case KeyCode::Thai_lekkao:
        return "Thai_lekkao";
    case KeyCode::Hangul_Kiyeog:
        return "Hangul_Kiyeog";
    case KeyCode::Hangul_SsangKiyeog:
        return "Hangul_SsangKiyeog";
    case KeyCode::Hangul_KiyeogSios:
        return "Hangul_KiyeogSios";
    case KeyCode::Hangul_Nieun:
        return "Hangul_Nieun";
    case KeyCode::Hangul_NieunJieuj:
        return "Hangul_NieunJieuj";
    case KeyCode::Hangul_NieunHieuh:
        return "Hangul_NieunHieuh";
    case KeyCode::Hangul_Dikeud:
        return "Hangul_Dikeud";
    case KeyCode::Hangul_SsangDikeud:
        return "Hangul_SsangDikeud";
    case KeyCode::Hangul_Rieul:
        return "Hangul_Rieul";
    case KeyCode::Hangul_RieulKiyeog:
        return "Hangul_RieulKiyeog";
    case KeyCode::Hangul_RieulMieum:
        return "Hangul_RieulMieum";
    case KeyCode::Hangul_RieulPieub:
        return "Hangul_RieulPieub";
    case KeyCode::Hangul_RieulSios:
        return "Hangul_RieulSios";
    case KeyCode::Hangul_RieulTieut:
        return "Hangul_RieulTieut";
    case KeyCode::Hangul_RieulPhieuf:
        return "Hangul_RieulPhieuf";
    case KeyCode::Hangul_RieulHieuh:
        return "Hangul_RieulHieuh";
    case KeyCode::Hangul_Mieum:
        return "Hangul_Mieum";
    case KeyCode::Hangul_Pieub:
        return "Hangul_Pieub";
    case KeyCode::Hangul_SsangPieub:
        return "Hangul_SsangPieub";
    case KeyCode::Hangul_PieubSios:
        return "Hangul_PieubSios";
    case KeyCode::Hangul_Sios:
        return "Hangul_Sios";
    case KeyCode::Hangul_SsangSios:
        return "Hangul_SsangSios";
    case KeyCode::Hangul_Ieung:
        return "Hangul_Ieung";
    case KeyCode::Hangul_Jieuj:
        return "Hangul_Jieuj";
    case KeyCode::Hangul_SsangJieuj:
        return "Hangul_SsangJieuj";
    case KeyCode::Hangul_Cieuc:
        return "Hangul_Cieuc";
    case KeyCode::Hangul_Khieuq:
        return "Hangul_Khieuq";
    case KeyCode::Hangul_Tieut:
        return "Hangul_Tieut";
    case KeyCode::Hangul_Phieuf:
        return "Hangul_Phieuf";
    case KeyCode::Hangul_Hieuh:
        return "Hangul_Hieuh";
    case KeyCode::Hangul_A:
        return "Hangul_A";
    case KeyCode::Hangul_AE:
        return "Hangul_AE";
    case KeyCode::Hangul_YA:
        return "Hangul_YA";
    case KeyCode::Hangul_YAE:
        return "Hangul_YAE";
    case KeyCode::Hangul_EO:
        return "Hangul_EO";
    case KeyCode::Hangul_E:
        return "Hangul_E";
    case KeyCode::Hangul_YEO:
        return "Hangul_YEO";
    case KeyCode::Hangul_YE:
        return "Hangul_YE";
    case KeyCode::Hangul_O:
        return "Hangul_O";
    case KeyCode::Hangul_WA:
        return "Hangul_WA";
    case KeyCode::Hangul_WAE:
        return "Hangul_WAE";
    case KeyCode::Hangul_OE:
        return "Hangul_OE";
    case KeyCode::Hangul_YO:
        return "Hangul_YO";
    case KeyCode::Hangul_U:
        return "Hangul_U";
    case KeyCode::Hangul_WEO:
        return "Hangul_WEO";
    case KeyCode::Hangul_WE:
        return "Hangul_WE";
    case KeyCode::Hangul_WI:
        return "Hangul_WI";
    case KeyCode::Hangul_YU:
        return "Hangul_YU";
    case KeyCode::Hangul_EU:
        return "Hangul_EU";
    case KeyCode::Hangul_YI:
        return "Hangul_YI";
    case KeyCode::Hangul_I:
        return "Hangul_I";
    case KeyCode::Hangul_J_Kiyeog:
        return "Hangul_J_Kiyeog";
    case KeyCode::Hangul_J_SsangKiyeog:
        return "Hangul_J_SsangKiyeog";
    case KeyCode::Hangul_J_KiyeogSios:
        return "Hangul_J_KiyeogSios";
    case KeyCode::Hangul_J_Nieun:
        return "Hangul_J_Nieun";
    case KeyCode::Hangul_J_NieunJieuj:
        return "Hangul_J_NieunJieuj";
    case KeyCode::Hangul_J_NieunHieuh:
        return "Hangul_J_NieunHieuh";
    case KeyCode::Hangul_J_Dikeud:
        return "Hangul_J_Dikeud";
    case KeyCode::Hangul_J_Rieul:
        return "Hangul_J_Rieul";
    case KeyCode::Hangul_J_RieulKiyeog:
        return "Hangul_J_RieulKiyeog";
    case KeyCode::Hangul_J_RieulMieum:
        return "Hangul_J_RieulMieum";
    case KeyCode::Hangul_J_RieulPieub:
        return "Hangul_J_RieulPieub";
    case KeyCode::Hangul_J_RieulSios:
        return "Hangul_J_RieulSios";
    case KeyCode::Hangul_J_RieulTieut:
        return "Hangul_J_RieulTieut";
    case KeyCode::Hangul_J_RieulPhieuf:
        return "Hangul_J_RieulPhieuf";
    case KeyCode::Hangul_J_RieulHieuh:
        return "Hangul_J_RieulHieuh";
    case KeyCode::Hangul_J_Mieum:
        return "Hangul_J_Mieum";
    case KeyCode::Hangul_J_Pieub:
        return "Hangul_J_Pieub";
    case KeyCode::Hangul_J_PieubSios:
        return "Hangul_J_PieubSios";
    case KeyCode::Hangul_J_Sios:
        return "Hangul_J_Sios";
    case KeyCode::Hangul_J_SsangSios:
        return "Hangul_J_SsangSios";
    case KeyCode::Hangul_J_Ieung:
        return "Hangul_J_Ieung";
    case KeyCode::Hangul_J_Jieuj:
        return "Hangul_J_Jieuj";
    case KeyCode::Hangul_J_Cieuc:
        return "Hangul_J_Cieuc";
    case KeyCode::Hangul_J_Khieuq:
        return "Hangul_J_Khieuq";
    case KeyCode::Hangul_J_Tieut:
        return "Hangul_J_Tieut";
    case KeyCode::Hangul_J_Phieuf:
        return "Hangul_J_Phieuf";
    case KeyCode::Hangul_J_Hieuh:
        return "Hangul_J_Hieuh";
    case KeyCode::Hangul_RieulYeorinHieuh:
        return "Hangul_RieulYeorinHieuh";
    case KeyCode::Hangul_SunkyeongeumMieum:
        return "Hangul_SunkyeongeumMieum";
    case KeyCode::Hangul_SunkyeongeumPieub:
        return "Hangul_SunkyeongeumPieub";
    case KeyCode::Hangul_PanSios:
        return "Hangul_PanSios";
    case KeyCode::Hangul_KkogjiDalrinIeung:
        return "Hangul_KkogjiDalrinIeung";
    case KeyCode::Hangul_SunkyeongeumPhieuf:
        return "Hangul_SunkyeongeumPhieuf";
    case KeyCode::Hangul_YeorinHieuh:
        return "Hangul_YeorinHieuh";
    case KeyCode::Hangul_AraeA:
        return "Hangul_AraeA";
    case KeyCode::Hangul_AraeAE:
        return "Hangul_AraeAE";
    case KeyCode::Hangul_J_PanSios:
        return "Hangul_J_PanSios";
    case KeyCode::Hangul_J_KkogjiDalrinIeung:
        return "Hangul_J_KkogjiDalrinIeung";
    case KeyCode::Hangul_J_YeorinHieuh:
        return "Hangul_J_YeorinHieuh";
    case KeyCode::Korean_Won:
        return "Korean_Won";
    case KeyCode::OE:
        return "OE";
    case KeyCode::oe:
        return "oe";
    case KeyCode::Ydiaeresis:
        return "Ydiaeresis";
    case KeyCode::EuroSign:
        return "EuroSign";
    case KeyCode::Duplicate:
        return "Duplicate";
    case KeyCode::FieldMark:
        return "FieldMark";
    case KeyCode::Right2:
        return "Right2";
    case KeyCode::Left2:
        return "Left2";
    case KeyCode::BackTab:
        return "BackTab";
    case KeyCode::EraseEOF:
        return "EraseEOF";
    case KeyCode::EraseInput:
        return "EraseInput";
    case KeyCode::Reset:
        return "Reset";
    case KeyCode::Quit:
        return "Quit";
    case KeyCode::PA1:
        return "PA1";
    case KeyCode::PA2:
        return "PA2";
    case KeyCode::PA3:
        return "PA3";
    case KeyCode::Test:
        return "Test";
    case KeyCode::Attn:
        return "Attn";
    case KeyCode::CursorBlink:
        return "CursorBlink";
    case KeyCode::AltCursor:
        return "AltCursor";
    case KeyCode::KeyClick:
        return "KeyClick";
    case KeyCode::Jump:
        return "Jump";
    case KeyCode::Ident:
        return "Ident";
    case KeyCode::Rule:
        return "Rule";
    case KeyCode::Copy:
        return "Copy";
    case KeyCode::Play:
        return "Play";
    case KeyCode::Setup:
        return "Setup";
    case KeyCode::Record:
        return "Record";
    case KeyCode::ChangeScreen:
        return "ChangeScreen";
    case KeyCode::DeleteWord:
        return "DeleteWord";
    case KeyCode::ExSelect:
        return "ExSelect";
    case KeyCode::CursorSelect:
        return "CursorSelect";
    case KeyCode::PrintScreen:
        return "PrintScreen";
    case KeyCode::Enter:
        return "3270_Enter";
    case KeyCode::ISO_Lock:
        return "ISO_Lock";
    case KeyCode::ISO_Level2_Latch:
        return "ISO_Level2_Latch";
    case KeyCode::ISO_Level3_Shift:
        return "ISO_Level3_Shift";
    case KeyCode::ISO_Level3_Latch:
        return "ISO_Level3_Latch";
    case KeyCode::ISO_Level3_Lock:
        return "ISO_Level3_Lock";
    case KeyCode::ISO_Group_Latch:
        return "ISO_Group_Latch";
    case KeyCode::ISO_Group_Lock:
        return "ISO_Group_Lock";
    case KeyCode::ISO_Next_Group:
        return "ISO_Next_Group";
    case KeyCode::ISO_Next_Group_Lock:
        return "ISO_Next_Group_Lock";
    case KeyCode::ISO_Prev_Group:
        return "ISO_Prev_Group";
    case KeyCode::ISO_Prev_Group_Lock:
        return "ISO_Prev_Group_Lock";
    case KeyCode::ISO_First_Group:
        return "ISO_First_Group";
    case KeyCode::ISO_First_Group_Lock:
        return "ISO_First_Group_Lock";
    case KeyCode::ISO_Last_Group:
        return "ISO_Last_Group";
    case KeyCode::ISO_Last_Group_Lock:
        return "ISO_Last_Group_Lock";
    case KeyCode::ISO_Level5_Shift:
        return "ISO_Level5_Shift";
    case KeyCode::ISO_Level5_Latch:
        return "ISO_Level5_Latch";
    case KeyCode::ISO_Level5_Lock:
        return "ISO_Level5_Lock";
    case KeyCode::ISO_Left_Tab:
        return "ISO_Left_Tab";
    case KeyCode::ISO_Move_Line_Up:
        return "ISO_Move_Line_Up";
    case KeyCode::ISO_Move_Line_Down:
        return "ISO_Move_Line_Down";
    case KeyCode::ISO_Partial_Line_Up:
        return "ISO_Partial_Line_Up";
    case KeyCode::ISO_Partial_Line_Down:
        return "ISO_Partial_Line_Down";
    case KeyCode::ISO_Partial_Space_Left:
        return "ISO_Partial_Space_Left";
    case KeyCode::ISO_Partial_Space_Right:
        return "ISO_Partial_Space_Right";
    case KeyCode::ISO_Set_Margin_Left:
        return "ISO_Set_Margin_Left";
    case KeyCode::ISO_Set_Margin_Right:
        return "ISO_Set_Margin_Right";
    case KeyCode::ISO_Release_Margin_Left:
        return "ISO_Release_Margin_Left";
    case KeyCode::ISO_Release_Margin_Right:
        return "ISO_Release_Margin_Right";
    case KeyCode::ISO_Release_Both_Margins:
        return "ISO_Release_Both_Margins";
    case KeyCode::ISO_Fast_Cursor_Left:
        return "ISO_Fast_Cursor_Left";
    case KeyCode::ISO_Fast_Cursor_Right:
        return "ISO_Fast_Cursor_Right";
    case KeyCode::ISO_Fast_Cursor_Up:
        return "ISO_Fast_Cursor_Up";
    case KeyCode::ISO_Fast_Cursor_Down:
        return "ISO_Fast_Cursor_Down";
    case KeyCode::ISO_Continuous_Underline:
        return "ISO_Continuous_Underline";
    case KeyCode::ISO_Discontinuous_Underline:
        return "ISO_Discontinuous_Underline";
    case KeyCode::ISO_Emphasize:
        return "ISO_Emphasize";
    case KeyCode::ISO_Center_Object:
        return "ISO_Center_Object";
    case KeyCode::ISO_Enter:
        return "ISO_Enter";
    case KeyCode::dead_grave:
        return "dead_grave";
    case KeyCode::dead_acute:
        return "dead_acute";
    case KeyCode::dead_circumflex:
        return "dead_circumflex";
    case KeyCode::dead_tilde:
        return "dead_tilde";
    case KeyCode::dead_macron:
        return "dead_macron";
    case KeyCode::dead_breve:
        return "dead_breve";
    case KeyCode::dead_abovedot:
        return "dead_abovedot";
    case KeyCode::dead_diaeresis:
        return "dead_diaeresis";
    case KeyCode::dead_abovering:
        return "dead_abovering";
    case KeyCode::dead_doubleacute:
        return "dead_doubleacute";
    case KeyCode::dead_caron:
        return "dead_caron";
    case KeyCode::dead_cedilla:
        return "dead_cedilla";
    case KeyCode::dead_ogonek:
        return "dead_ogonek";
    case KeyCode::dead_iota:
        return "dead_iota";
    case KeyCode::dead_voiced_sound:
        return "dead_voiced_sound";
    case KeyCode::dead_semivoiced_sound:
        return "dead_semivoiced_sound";
    case KeyCode::dead_belowdot:
        return "dead_belowdot";
    case KeyCode::dead_hook:
        return "dead_hook";
    case KeyCode::dead_horn:
        return "dead_horn";
    case KeyCode::dead_stroke:
        return "dead_stroke";
    case KeyCode::dead_abovecomma:
        return "dead_abovecomma";
    case KeyCode::dead_abovereversedcomma:
        return "dead_abovereversedcomma";
    case KeyCode::dead_doublegrave:
        return "dead_doublegrave";
    case KeyCode::dead_belowring:
        return "dead_belowring";
    case KeyCode::dead_belowmacron:
        return "dead_belowmacron";
    case KeyCode::dead_belowcircumflex:
        return "dead_belowcircumflex";
    case KeyCode::dead_belowtilde:
        return "dead_belowtilde";
    case KeyCode::dead_belowbreve:
        return "dead_belowbreve";
    case KeyCode::dead_belowdiaeresis:
        return "dead_belowdiaeresis";
    case KeyCode::dead_invertedbreve:
        return "dead_invertedbreve";
    case KeyCode::dead_belowcomma:
        return "dead_belowcomma";
    case KeyCode::dead_currency:
        return "dead_currency";
    case KeyCode::AccessX_Enable:
        return "AccessX_Enable";
    case KeyCode::AccessX_Feedback_Enable:
        return "AccessX_Feedback_Enable";
    case KeyCode::RepeatKeys_Enable:
        return "RepeatKeys_Enable";
    case KeyCode::SlowKeys_Enable:
        return "SlowKeys_Enable";
    case KeyCode::BounceKeys_Enable:
        return "BounceKeys_Enable";
    case KeyCode::StickyKeys_Enable:
        return "StickyKeys_Enable";
    case KeyCode::MouseKeys_Enable:
        return "MouseKeys_Enable";
    case KeyCode::MouseKeys_Accel_Enable:
        return "MouseKeys_Accel_Enable";
    case KeyCode::Overlay1_Enable:
        return "Overlay1_Enable";
    case KeyCode::Overlay2_Enable:
        return "Overlay2_Enable";
    case KeyCode::AudibleBell_Enable:
        return "AudibleBell_Enable";
    case KeyCode::dead_a:
        return "dead_a";
    case KeyCode::dead_A:
        return "dead_A";
    case KeyCode::dead_e:
        return "dead_e";
    case KeyCode::dead_E:
        return "dead_E";
    case KeyCode::dead_i:
        return "dead_i";
    case KeyCode::dead_I:
        return "dead_I";
    case KeyCode::dead_o:
        return "dead_o";
    case KeyCode::dead_O:
        return "dead_O";
    case KeyCode::dead_u:
        return "dead_u";
    case KeyCode::dead_U:
        return "dead_U";
    case KeyCode::dead_small_schwa:
        return "dead_small_schwa";
    case KeyCode::dead_capital_schwa:
        return "dead_capital_schwa";
    case KeyCode::dead_greek:
        return "dead_greek";
    case KeyCode::ch:
        return "ch";
    case KeyCode::Ch:
        return "Ch";
    case KeyCode::CH:
        return "CH";
    case KeyCode::c_h:
        return "c_h";
    case KeyCode::C_h:
        return "C_h";
    case KeyCode::C_H:
        return "C_H";
    case KeyCode::firstVirtualScreen:
        return "first_Virtual_Screen";
    case KeyCode::prevVirtualScreen:
        return "prevVirtualScreen";
    case KeyCode::nextVirtualScreen:
        return "nextVirtualScreen";
    case KeyCode::lastVirtualScreen:
        return "lastVirtualScreen";
    case KeyCode::terminateServer:
        return "terminateServer";
    case KeyCode::pointerLeft:
        return "pointerLeft";
    case KeyCode::pointerRight:
        return "pointerRight";
    case KeyCode::pointerUp:
        return "pointerUp";
    case KeyCode::pointerDown:
        return "pointerDown";
    case KeyCode::pointerUpLeft:
        return "pointerUpLeft";
    case KeyCode::pointerUpRight:
        return "pointerUpRight";
    case KeyCode::pointerDownLeft:
        return "pointerDownLeft";
    case KeyCode::pointerDownRight:
        return "pointerDownRight";
    case KeyCode::pointerButtonDflt:
        return "pointerButtonDflt";
    case KeyCode::pointerButton1:
        return "pointerButton1";
    case KeyCode::pointerButton2:
        return "pointerButton2";
    case KeyCode::pointerButton3:
        return "pointerButton3";
    case KeyCode::pointerButton4:
        return "pointerButton4";
    case KeyCode::pointerButton5:
        return "pointerButton5";
    case KeyCode::pointerDblClickDflt:
        return "pointerDblClickDflt";
    case KeyCode::pointerDblClick1:
        return "pointerDblClick1";
    case KeyCode::pointerDblClick2:
        return "pointerDblClick2";
    case KeyCode::pointerDblClick3:
        return "pointerDblClick3";
    case KeyCode::pointerDblClick4:
        return "pointerDblClick4";
    case KeyCode::pointerDblClick5:
        return "pointerDblClick5";
    case KeyCode::pointerDragDflt:
        return "pointerDragDflt";
    case KeyCode::pointerDrag1:
        return "pointerDrag1";
    case KeyCode::pointerDrag2:
        return "pointerDrag2";
    case KeyCode::pointerDrag3:
        return "pointerDrag3";
    case KeyCode::pointerDrag4:
        return "pointerDrag4";
    case KeyCode::pointerEnableKeys:
        return "pointerEnableKeys";
    case KeyCode::pointerAccelerate:
        return "pointerAccelerate";
    case KeyCode::pointerDfltBtnNext:
        return "pointerDfltBtnNext";
    case KeyCode::pointerDfltBtnPrev:
        return "pointerDfltBtnPrev";
    case KeyCode::pointerDrag5:
        return "pointerDrag5";
    case KeyCode::backSpace:
        return "backSpace";
    case KeyCode::tab:
        return "tab";
    case KeyCode::linefeed:
        return "linefeed";
    case KeyCode::clear:
        return "clear";
    case KeyCode::returnKey:
        return "returnKey";
    case KeyCode::pause:
        return "pause";
    case KeyCode::scrollLock:
        return "scrollLock";
    case KeyCode::sysReq:
        return "sysReq";
    case KeyCode::escape:
        return "escape";
    case KeyCode::multikey:
        return "multikey";
    case KeyCode::kanji:
        return "kanji";
    case KeyCode::muhenkan:
        return "muhenkan";
    case KeyCode::henkanMode:
        return "henkanMode";
    case KeyCode::romaji:
        return "romaji";
    case KeyCode::hiragana:
        return "hiragana";
    case KeyCode::katakana:
        return "katakana";
    case KeyCode::hiraganaKatakana:
        return "hiraganaKatakana";
    case KeyCode::zenkaku:
        return "zenkaku";
    case KeyCode::hankaku:
        return "hankaku";
    case KeyCode::zenkakuHankaku:
        return "zenkaku_Hankaku";
    case KeyCode::touroku:
        return "touroku";
    case KeyCode::massyo:
        return "Massyo";
    case KeyCode::kanaLock:
        return "kanaLock";
    case KeyCode::kanaShift:
        return "kanaShift";
    case KeyCode::eisuShift:
        return "eisuShift";
    case KeyCode::eisutoggle:
        return "eisutoggle";
    case KeyCode::hangul:
        return "hangul";
    case KeyCode::hangulStart:
        return "hangulStart";
    case KeyCode::hangulEnd:
        return "hangulEnd";
    case KeyCode::hangulHanja:
        return "hangulHanja";
    case KeyCode::hangulJamo:
        return "hangulJamo";
    case KeyCode::hangulRomaja:
        return "hangulRomaja";
    case KeyCode::codeinput:
        return "codeinput";
    case KeyCode::hangulJeonja:
        return "hangulJeonja";
    case KeyCode::hangulBanja:
        return "hangulBanja";
    case KeyCode::hangulPreHanja:
        return "hangulPreHanja";
    case KeyCode::hangulPostHanja:
        return "hangulPostHanja";
    case KeyCode::singleCandidate:
        return "singleCandidate";
    case KeyCode::multipleCandidate:
        return "multipleCandidate";
    case KeyCode::previousCandidate:
        return "previousCandidate";
    case KeyCode::hangulSpecial:
        return "hangulSpecial";
    case KeyCode::home:
        return "home";
    case KeyCode::left:
        return "left";
    case KeyCode::up:
        return "up";
    case KeyCode::right:
        return "right";
    case KeyCode::down:
        return "down";
    case KeyCode::prior:
        return "prior";
    case KeyCode::next:
        return "next";
    case KeyCode::end:
        return "end";
    case KeyCode::begin:
        return "begin";
    case KeyCode::select:
        return "select";
    case KeyCode::print:
        return "print";
    case KeyCode::execute:
        return "execute";
    case KeyCode::insert:
        return "insert";
    case KeyCode::undo:
        return "undo";
    case KeyCode::redo:
        return "redo";
    case KeyCode::menu:
        return "menu";
    case KeyCode::find:
        return "find";
    case KeyCode::cancel:
        return "cancel";
    case KeyCode::help:
        return "help";
    case KeyCode::breakKey:
        return "breakKey";
    case KeyCode::modeswitch:
        return "modeswitch";
    case KeyCode::numLock:
        return "numLock";
    case KeyCode::kpSpace:
        return "kpSpace";
    case KeyCode::kpTab:
        return "kpTab";
    case KeyCode::kpEnter:
        return "kpEnter";
    case KeyCode::kpF1:
        return "kpF1";
    case KeyCode::kpF2:
        return "kpF2";
    case KeyCode::kpF3:
        return "kpF3";
    case KeyCode::kpF4:
        return "kpF4";
    case KeyCode::kpHome:
        return "kpHome";
    case KeyCode::kpLeft:
        return "kpLeft";
    case KeyCode::kpUp:
        return "kpUp";
    case KeyCode::kpRight:
        return "kpRight";
    case KeyCode::kpDown:
        return "kpDown";
    case KeyCode::kpPrior:
        return "kpPrior";
    case KeyCode::kpNext:
        return "kpNext";
    case KeyCode::kpEnd:
        return "kpEnd";
    case KeyCode::kpBegin:
        return "kpBegin";
    case KeyCode::kpInsert:
        return "kpInsert";
    case KeyCode::kpDelete:
        return "kpDelete";
    case KeyCode::kpMultiply:
        return "kpMultiply";
    case KeyCode::kpAdd:
        return "kpAdd";
    case KeyCode::kpSeparator:
        return "kpSeparator";
    case KeyCode::kpSubtract:
        return "kpSubtract";
    case KeyCode::kpDecimal:
        return "kpDecimal";
    case KeyCode::kpDivide:
        return "kpDivide";
    case KeyCode::kp0:
        return "kp0";
    case KeyCode::kp1:
        return "kp1";
    case KeyCode::kp2:
        return "kp2";
    case KeyCode::kp3:
        return "kp3";
    case KeyCode::kp4:
        return "kp4";
    case KeyCode::kp5:
        return "kp5";
    case KeyCode::kp6:
        return "kp6";
    case KeyCode::kp7:
        return "kp7";
    case KeyCode::kp8:
        return "kp8";
    case KeyCode::kp9:
        return "kp9";
    case KeyCode::kpEqual:
        return "kpEqual";
    case KeyCode::f1:
        return "f1";
    case KeyCode::f2:
        return "f2";
    case KeyCode::f3:
        return "f3";
    case KeyCode::f4:
        return "f4";
    case KeyCode::f5:
        return "f5";
    case KeyCode::f6:
        return "f6";
    case KeyCode::f7:
        return "f7";
    case KeyCode::f8:
        return "f8";
    case KeyCode::f9:
        return "f9";
    case KeyCode::f10:
        return "f10";
    case KeyCode::f11:
        return "f11";
    case KeyCode::f12:
        return "f12";
    case KeyCode::f13:
        return "f13";
    case KeyCode::f14:
        return "f14";
    case KeyCode::f15:
        return "f15";
    case KeyCode::f16:
        return "f16";
    case KeyCode::f17:
        return "f17";
    case KeyCode::f18:
        return "f18";
    case KeyCode::f19:
        return "f19";
    case KeyCode::f20:
        return "f20";
    case KeyCode::f21:
        return "f21";
    case KeyCode::f22:
        return "f22";
    case KeyCode::f23:
        return "f23";
    case KeyCode::f24:
        return "f24";
    case KeyCode::f25:
        return "f25";
    case KeyCode::f26:
        return "f26";
    case KeyCode::f27:
        return "f27";
    case KeyCode::f28:
        return "f28";
    case KeyCode::f29:
        return "f29";
    case KeyCode::f30:
        return "f30";
    case KeyCode::f31:
        return "f31";
    case KeyCode::f32:
        return "f32";
    case KeyCode::f33:
        return "f33";
    case KeyCode::f34:
        return "f34";
    case KeyCode::f35:
        return "f35";
    case KeyCode::shiftL:
        return "shiftL";
    case KeyCode::shiftR:
        return "shiftR";
    case KeyCode::controlL:
        return "controlL";
    case KeyCode::controlR:
        return "controlR";
    case KeyCode::capsLock:
        return "capsLock";
    case KeyCode::shiftLock:
        return "shiftLock";
    case KeyCode::metaL:
        return "metaL";
    case KeyCode::metaR:
        return "metaR";
    case KeyCode::altL:
        return "altL";
    case KeyCode::altR:
        return "altR";
    case KeyCode::superL:
        return "superL";
    case KeyCode::superR:
        return "superR";
    case KeyCode::hyperL:
        return "hyperL";
    case KeyCode::hyperR:
        return "hyperR";
    case KeyCode::braille_dot_1:
        return "braille_dot_1";
    case KeyCode::braille_dot_2:
        return "braille_dot_2";
    case KeyCode::braille_dot_3:
        return "braille_dot_3";
    case KeyCode::braille_dot_4:
        return "braille_dot_4";
    case KeyCode::braille_dot_5:
        return "braille_dot_5";
    case KeyCode::braille_dot_6:
        return "braille_dot_6";
    case KeyCode::braille_dot_7:
        return "braille_dot_7";
    case KeyCode::braille_dot_8:
        return "braille_dot_8";
    case KeyCode::braille_dot_9:
        return "braille_dot_9";
    case KeyCode::braille_dot_10:
        return "braille_dot_10";
    };

    return "<unknown>";
}

} // ase

